=== TheoLeCalvar/castle/scene.dtd
<!ELEMENT scene (materiaux, lumieres, pieces) >
<!ATTLIST scene nom CDATA #REQUIRED >


<!ELEMENT materiaux (material+) >

<!ELEMENT material (ambient, diffuse, specular, emissive, texture?) >
<!ATTLIST material nom ID #REQUIRED >

<!ELEMENT ambient EMPTY >
<!ATTLIST ambient 
			r CDATA #REQUIRED
			g CDATA #REQUIRED
			b CDATA #REQUIRED
			a CDATA #IMPLIED >

<!ELEMENT diffuse EMPTY >
<!ATTLIST diffuse 
			r CDATA #REQUIRED
			g CDATA #REQUIRED
			b CDATA #REQUIRED
			a CDATA #IMPLIED >			

<!ELEMENT specular EMPTY >
<!ATTLIST specular 
			r CDATA #REQUIRED
			g CDATA #REQUIRED
			b CDATA #REQUIRED
			a CDATA #IMPLIED 
			s CDATA #REQUIRED >

<!ELEMENT emissive EMPTY >
<!ATTLIST emissive 
			r CDATA #REQUIRED
			g CDATA #REQUIRED
			b CDATA #REQUIRED
			a CDATA #IMPLIED >

<!ELEMENT texture EMPTY >
<!ATTLIST texture src CDATA #REQUIRED >

<!ELEMENT lumieres (lumiere+) >

<!ELEMENT lumiere (position) >
<!ATTLIST lumiere 
			nom ID #REQUIRED 
			mat IDREF "defaut"	>


<!ELEMENT position EMPTY >
<!ATTLIST position 
			repere (world|model|view) #IMPLIED
			relatif IDREF #IMPLIED
			x CDATA #REQUIRED
			y CDATA #REQUIRED
			z CDATA #REQUIRED >

<!ELEMENT pieces (piece+) >

<!ELEMENT piece (dimension, position, murs, objets) >
<!ATTLIST piece nom ID #REQUIRED >

<!ELEMENT dimension EMPTY >
<!ATTLIST dimension 
			longueur CDATA #REQUIRED
			largeur CDATA #REQUIRED
			hauteur CDATA #REQUIRED >
			
<!ELEMENT murs (mur) >

<!ELEMENT mur EMPTY >
<!ATTLIST mur 
			cote (avant|arriere|gauche|droit|haut|bas) #REQUIRED
			mat IDREF "defaut" >

<!ELEMENT objets (objet+) >

<!ELEMENT objet (position, objet*) >
<!ATTLIST objet 
			nom ID #REQUIRED
			mat IDREF "defaut"
			modele CDATA #REQUIRED
			Xrot CDATA #IMPLIED
			Yrot CDATA #IMPLIED
			Zrot CDATA #IMPLIED >

=== TheoLeCalvar/castle/Ressource/test.xml
<?xml version='1.0' encoding="utf-8" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene nom="Main">
	<camera>
		<position x="40" y="15" z="0" />
	</camera>

	<materiaux>
	</materiaux>

	<lumieres>
		<lumiere nom="Light1" >
			<position x="1" y="10" z="4" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="0.8" g="0.8" b="0.8" />
			<specular r="0.8" g="0.8" b="0.8" />
		</lumiere>
	</lumieres>

	<shaders>
		<shader nom="bump" fragment="shaders/bump.frag" vertex="shaders/test.vert" />
	</shaders>

	<pieces>
		<piece nom="piÃ¨ce1" shader="bump" mat="Mat1">
			<dimension width="12" length="10" height="10" />
			<position x="0" y="0" z="0" />

			<objets>

				<objet nom="objet2" modele="modeles/twilight/twilight.obj" Xrot="0" Yrot="90" Zrot="0" >
					<position x="0" y="0" z="0" />
				</objet>


			</objets>
		</piece>
	</pieces>
</scene>

=== TheoLeCalvar/castle/scene.xml
<?xml version='1.0' encoding="utf-8" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene nom="Main">
	<camera>
		<position repere="world" x="12.45" y="1" z="0" />
	</camera>

	<materiaux>
		<material nom="Mat1">
			<ambient r="10" g="10" b="10" a="1.0" />
			<diffuse r="124" g="120" b="0" a="1.0" />
			<specular r="12" g="123" b="24" a="1.0" s="32" />
			<emissive r="123" g="145" b="12" a="125" />
			<texture src="path" /> 
		</material>
		<material nom="Mat2">
			<ambient r="10" g="10" b="10" a="1.0" />
			<diffuse r="124" g="120" b="0" a="1.0" />
			<specular r="12" g="123" b="24" a="1.0" s="32" />
			<emissive r="123" g="145" b="12" a="125" />
		</material>
		<material nom="Mat2">
			<ambient r="10" g="10" b="10" a="1.0" />
			<diffuse r="124" g="120" b="0" a="1.0" />
			<specular r="12" g="123" b="24" a="1.0" s="32" />
			<emissive r="123" g="145" b="12" a="125" />
		</material>
	</materiaux>

	<lumieres>
		<lumiere nom="Light1" mat="Mat2" >
<!-- 			<position repere="world|eye|model" x="1" y="1" z="1" /> -->
			<position repere="world" x="1" y="1" z="1" />
		</lumiere>
		<lumiere nom="Light2" mat="Mat1" >
			<position repere="world" x="1" y="1" z="4" />
		</lumiere>
	</lumieres>

	<pieces>
		<piece nom="piÃ¨ce1">
			<dimension largeur="12" longueur="1" hauteur="3" />
			<position repere="world" x="0" y="0" z="0" />
			<murs>
<!--				<mur cote="avant|arriere|droite|gauche|haut|bas" mat="Mat1" /> -->
					<mur cote="avant" mat="Mat1" />
			</murs>

			<objets>
				<objet nom="objet1" mat="Mat2" modele="chaise" Xrot="12" Yrot="3" Zrot="0" >
					<position x="12" y="1" z="0" />
				</objet>
				<objet nom="objet2" mat="Mat2" modele="lavabo" >
					<position relatif="objet1" x="1" y="5" z="0" />
				</objet>
			</objets>
		</piece>
	</pieces>
</scene>

=== TheoLeCalvar/castle/Ressource/shaders/scene.xml
<?xml version='1.0' encoding="utf-8" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene nom="Main">
	<camera>
		<position x="40" y="15" z="0" />
	</camera>

	<materiaux>
		<material nom="Mat1">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.4" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<texture src="textures/stonebrick.png" type="diffuse" /> 
			<texture src="textures/stonebrick_normal.png" type="normal" />
		</material>
		<material nom="Mat2">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.2" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" /> 
			<texture src="textures/stonebrick_mossy.png" type="diffuse" />
		</material>
		<material nom="Mat3">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.2" b="0.8" a="1.0" />
			<specular r="0.8" g="0.0" b="0.2" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<!-- <texture src="textures/stonebrick.png" />  -->
		</material>
		<material nom="wall" >
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<texture src="textures/Chimeny.JPG" type="diffuse" />
			<texture src="textures/Chimeny_N.JPG" type="normal" />
		</material>
		<material nom="neutre">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" /> 
		</material>
	</materiaux>

	<lumieres>
		<lumiere nom="Light1" >
			<position x="1" y="10" z="4" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="1.0" g="0.0" b="0.0" />
			<specular r="1.0" g="0.0" b="0.0" />
		</lumiere>
		<lumiere nom="Light2" >
			<position x="14" y="8" z="22" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="0.0" g="1.0" b="0.0" />
			<specular r="0.0" g="1.0" b="0.0" />
		</lumiere>
		<lumiere nom="Light3" >
			<position x="5" y="7" z="7" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="0.0" g="0.0" b="1.0" />
			<specular r="0.0" g="0.0" b="1.0" />
		</lumiere>

		<lumiere nom="Light4" >
			<position x="15" y="6" z="4" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="1.0" g="1.0" b="0.0" />
			<specular r="1.0" g="1.0" b="0.0" />
		</lumiere>

		<lumiere nom="Light5" >
			<position x="-12" y="2" z="-2" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="1.0" g="0.0" b="1.0" />
			<specular r="1.0" g="0.0" b="0.0" />
		</lumiere>
		<lumiere nom="Light6" >
			<position x="-2" y="15" z="0" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="0.0" g="1.0" b="1.0" />
			<specular r="0.0" g="1.0" b="1.0" />
		</lumiere>

		<lumiere nom="Light7" >
			<position x="23" y="10" z="-12" />
			<ambient r="0.2" g="0.2" b="0.2" />
			<diffuse r="1.0" g="1.0" b="1.0" />
			<specular r="1.0" g="1.0" b="1.0" />
		</lumiere>
	</lumieres>

	<shaders>
		<shader nom="test" fragment="shaders/test.frag" vertex="shaders/test.vert" />
		<shader nom="bump" fragment="shaders/bump.frag" vertex="shaders/test.vert" />
	</shaders>

	<postProcess>
		<shader nom="mosaique" vertex="shaders/quad.vert" fragment="shaders/mosaique.frag" />
		<shader nom="sepia" vertex="shaders/base.vert" fragment="shaders/sepia.frag" />
		<shader nom="noir et blanc" vertex="shaders/base.vert" fragment="shaders/grayScale.frag" />
		<shader nom="flou gaussien" vertex="shaders/base.vert" fragment="shaders/gaussianBlur.frag" />
		<shader nom="edge detection" vertex="shaders/base.vert" fragment="shaders/edgeDetect.frag" />
		<shader nom="invert" vertex="shaders/base.vert" fragment="shaders/invertColor.frag" />
	</postProcess>

	<pieces>
		<piece nom="piÃ¨ce1" shader="test" mat="Mat1">
			<dimension width="12" length="10" height="10" />
			<position x="0" y="0" z="0" />
			<murs>
					<mur cote="avant" mat="Mat2" >
						<fenetre x="2" y="3" width="1" height="2" />
					</mur>
					<mur cote="bas" mat="Mat2" >
						<fenetre x="1" y="2" width="1" height="2" />
						<fenetre x="4" y="6" width="1" height="2" />
					</mur>
					<mur cote="haut" mat="Mat2" >
					</mur>
					<mur cote="arriere" mat="Mat3" >
						<fenetre x="0" y="0" width="1" height="1" />
					</mur>
					<mur cote="droite" />
					<mur cote="gauche" >
						<fenetre x="5" y="0" width="2" height="1" />
					</mur>
			</murs>

			<objets>
				<objet nom="objet1" modele="modeles/bun_zipper.ply" Xrot="90" Yrot="90" Zrot="0" >
					<position x="5" y="7" z="0" />
				</objet>

				<objet nom="objet2" modele="modeles/twilight/twilight.obj" Xrot="0" Yrot="90" Zrot="0" >
					<position x="0" y="0" z="0" />
				</objet>

				<objet nom="objet3" modele="modeles/susanne/susanne.obj" >
					<position x="1" y="5" z="7" />
				</objet>

<!-- 				<objet nom="miku" modele="modeles/miku/mikuA.obj" >
					<position x="1" y="5" z="7" />
				</objet> -->

			</objets>
		</piece>
		<piece nom="piece2" shader="bump" mat="wall">
			<dimension width="20" length="30" height="20" />
			<position x="10" y="3" z="20" />
			<murs>
				<mur cote="avant" mat="Mat1" >
					<fenetre x="1" y="2" width="1" height="2" />
				</mur>
				<mur cote="bas" mat="Mat1" >
					<fenetre x="4" y="6" width="1" height="2" />
				</mur>
				<mur cote="haut" mat="Mat1" >
					<fenetre x="2" y="3" width="1" height="2" />
				</mur>
				<mur cote="arriere" >
				</mur>
				<mur cote="droite" />
				<mur cote="gauche" >
					<fenetre x="5" y="0" width="2" height="1" />
				</mur>
			</murs>
			<objets>
				<objet nom="plante1" modele="modeles/sphere/sphere.obj" >
					<position x="10" y="10" z="4" />
				</objet>

				<objet nom="ibjet54" modele="modeles/flutter/flutter.obj" Xrot="0" Yrot="90" Zrot="0" >
					<position x="0" y="0" z="0" />
				</objet>

				<objet nom="yolo" modele="modeles/flutter/flutter.obj" Xrot="0" Yrot="90" Zrot="0" >
					<position x="5" y="5" z="5" />
				</objet>
			</objets>
		</piece>
	</pieces>
</scene>

=== TheoLeCalvar/castle/scene/scene.xml
<?xml version='1.0' encoding="utf-8" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene nom="Main">
	<camera>
		<position repere="world" x="12.45" y="1" z="0" />
	</camera>

	<materiaux>
		<material nom="Mat1">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<texture src="path" /> 
		</material>
	</materiaux>

	<lumieres>
		<lumiere nom="Light2" mat="Mat1" >
			<position repere="world" x="1" y="1" z="4" />
		</lumiere>
	</lumieres>

	<shaders>
		<shader nom="test" fragment="test.frag" vertex="test.vert" />
	</shaders>

	<pieces>
		<piece nom="piÃ¨ce1" shader="test">
			<dimension width="12" length="5" height="3" />
			<position repere="world" x="0" y="0" z="0" />
			<murs>
				<!-- <mur cote="avant|arriere|droite|gauche|haut|bas" mat="Mat1" />  -->
					<mur cote="avant" mat="Mat1" >
						<fenetre x="2" y="3" width="1" height="2" />
					</mur>
			</murs>

			<objets>
				<objet nom="objet1" mat="Mat2" modele="chaise" Xrot="12" Yrot="3" Zrot="0" >
					<position x="12" y="1" z="0" />
				</objet>
				<objet nom="objet2" mat="Mat2" modele="lavabo" >
					<position relatif="objet1" x="1" y="5" z="0" />
				</objet>
			</objets>
		</piece>
		<piece nom="piece2" >
		</piece>
	</pieces>
</scene>

=== TheoLeCalvar/castle/Ressource/scene.xml
<?xml version='1.0' encoding="utf-8" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene nom="Main">
	<camera>
		<position repere="world" x="40" y="15" z="0" />
	</camera>

	<materiaux>
		<material nom="Mat1">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.4" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<texture src="textures/stonebrick.png" location="0" /> 
			<texture src="textures/stonebrick_normal.png" location="1" />
		</material>
		<material nom="Mat2">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.2" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" /> 
			<texture src="textures/stonebrick_mossy.png" location="0" />
		</material>
		<material nom="Mat3">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.2" b="0.8" a="1.0" />
			<specular r="0.8" g="0.0" b="0.2" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<!-- <texture src="textures/stonebrick.png" />  -->
		</material>
		<material nom="wall" >
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" />
			<texture src="textures/Chimeny.JPG" location="0" />
			<texture src="textures/Chimeny_N.JPG" location="1" />
		</material>
		<material nom="neutre">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="0.8" g="0.8" b="0.8" a="1.0" />
			<specular r="0.8" g="0.8" b="0.8" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" /> 
		</material>
		<material nom="Light1">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="1.0" g="1.0" b="1.0" a="1.0" />
			<specular r="1.0" g="0.0" b="0.0" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" /> 
		</material>
		<material nom="Light2">
			<ambient r="0.2" g="0.2" b="0.2" a="1.0" />
			<diffuse r="1.0" g="1.0" b="1.0" a="1.0" />
			<specular r="0.0" g="0.0" b="1.0" a="1.0" s="32" />
			<emissive r="0.0" g="0.0" b="0.0" a="0.0" /> 
		</material>
	</materiaux>

	<lumieres>
		<lumiere nom="Light2" mat="Light2" num="0" >
			<position repere="world" x="1" y="10" z="4" />
		</lumiere>
		<lumiere nom="Light1" mat="Light1" num="1" >
			<position x="14" y="8" z="22" />
		</lumiere>
	</lumieres>

	<shaders>
		<shader nom="test" fragment="shaders/test.frag" vertex="shaders/test.vert" />
		<shader nom="bump" fragment="shaders/bump.frag" vertex="shaders/test.vert" />
	</shaders>

	<pieces>
		<piece nom="piÃ¨ce1" shader="test" mat="Mat1">
			<dimension width="12" length="10" height="10" />
			<position repere="world" x="0" y="0" z="0" />
			<murs>
					<mur cote="avant" mat="Mat2" >
						<fenetre x="2" y="3" width="1" height="2" />
					</mur>
					<mur cote="bas" mat="Mat2" >
						<fenetre x="1" y="2" width="1" height="2" />
						<fenetre x="4" y="6" width="1" height="2" />
					</mur>
					<mur cote="haut" mat="Mat2" >
					</mur>
					<mur cote="arriere" mat="Mat3" >
						<fenetre x="0" y="0" width="1" height="1" />
					</mur>
					<mur cote="droite" />
					<mur cote="gauche" >
						<fenetre x="5" y="0" width="2" height="1" />
					</mur>
			</murs>

			<objets>
				<objet nom="objet1" mat="Mat3" modele="modeles/bun_zipper.ply" Xrot="90" Yrot="90" Zrot="0" >
					<position x="5" y="7" z="0" />
				</objet>

				<objet nom="objet2" mat="Mat2" modele="modeles/twilight.obj" Xrot="0" Yrot="90" Zrot="0" >
					<position x="0" y="0" z="0" />
				</objet>

				<objet nom="objet3" mat="Mat3" modele="modeles/susanne.obj" >
					<position x="1" y="5" z="7" />
				</objet>
<!-- 				<objet nom="objet2" mat="Mat2" modele="lavabo" >
					<position relatif="objet1" x="1" y="5" z="0" />
				</objet> -->
			</objets>
		</piece>
		<piece nom="piece2" shader="bump" mat="wall">
			<dimension width="20" length="30" height="20" />
			<position repere="world" x="10" y="3" z="20" />
			<murs>
				<mur cote="avant" mat="Mat1" >
					<fenetre x="1" y="2" width="1" height="2" />
				</mur>
				<mur cote="bas" mat="Mat1" >
					<fenetre x="4" y="6" width="1" height="2" />
				</mur>
				<mur cote="haut" mat="Mat1" >
					<fenetre x="2" y="3" width="1" height="2" />
				</mur>
				<mur cote="arriere" >
				</mur>
				<mur cote="droite" />
				<mur cote="gauche" >
					<fenetre x="5" y="0" width="2" height="1" />
				</mur>
			</murs>
			<objets>
				<objet nom="plante1" modele="modeles/sphere.obj" >
					<position x="10" y="10" z="4" />
				</objet>
			</objets>
		</piece>
	</pieces>
</scene>
